import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer class="footer_footer__wxdzN">
          <a target="_blank" href="https://beian.miit.gov.cn/#/Integrated/index">浙ICP备17015491号-6</a>
          <a href="/docs/agreement_user">服务协议</a>
          <a href="/docs/agreement_private">隐私协议</a>
          <a href="/docs/rule">社区规则</a>
        </footer>
      </body>

    </html>
  )
}
